[package]
name = "pbirch"
version = "0.1.0"
authors = ["Chris McKinney <ntd5@tachibanatech.com>"]

[dependencies]
csv = "1"
enum-repr = { path = "enum-repr" }
rand = "0.6"

[dev-dependencies]
libc = "^0.2.42"
